//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hainadeblanaSite.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hainadeblanaEntities : DbContext
    {
        public hainadeblanaEntities()
            : base("name=hainadeblanaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adresa_Facturare> Adresa_Facturare { get; set; }
        public virtual DbSet<Adresa_Livrare> Adresa_Livrare { get; set; }
        public virtual DbSet<Categorii_Produse> Categorii_Produse { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Comanda> Comanda { get; set; }
        public virtual DbSet<Factura> Factura { get; set; }
        public virtual DbSet<Produs> Produs { get; set; }
        public virtual DbSet<ProdusComanda> ProdusComanda { get; set; }
        public virtual DbSet<ProdusImagine> ProdusImagine { get; set; }
    }
}
