//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HainadeblanaSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produs()
        {
            this.ProdusComanda = new HashSet<ProdusComanda>();
            this.ProdusImagine = new HashSet<ProdusImagine>();
        }
    
        public int ProdusID { get; set; }
        public string NumeProdus { get; set; }
        public decimal Pret { get; set; }
        public string Descriere { get; set; }
        public Nullable<int> CategorieID { get; set; }
    
        public virtual Categorii_Produse Categorii_Produse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProdusComanda> ProdusComanda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProdusImagine> ProdusImagine { get; set; }
    }
}
