//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hainadeblanaSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdusComanda
    {
        public int ProdusComandaID { get; set; }
        public Nullable<int> ComandaID { get; set; }
        public Nullable<int> ProdusID { get; set; }
    
        public virtual Comanda Comanda { get; set; }
        public virtual Produs Produs { get; set; }
    }
}
